config/routes.rb
Rails.application.routes.draw do
  resources :virtual_aliases
  resources :virtual_users
  resources :virtual_domains
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/virtual_alias.rb
class VirtualAlias < ApplicationRecord
  belongs_to :virtual_domain
end

app/models/virtual_domain.rb
class VirtualDomain < ApplicationRecord
end

app/models/virtual_user.rb
class VirtualUser < ApplicationRecord
  belongs_to :virtual_domain
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/virtual_aliases_controller.rb
class VirtualAliasesController < ApplicationController
  before_action :set_virtual_alias, only: [:show, :edit, :update, :destroy]

  # GET /virtual_aliases
  # GET /virtual_aliases.json
  def index
    @virtual_aliases = VirtualAlias.all
  end

  # GET /virtual_aliases/1
  # GET /virtual_aliases/1.json
  def show
  end

  # GET /virtual_aliases/new
  def new
    @virtual_alias = VirtualAlias.new
  end

  # GET /virtual_aliases/1/edit
  def edit
  end

  # POST /virtual_aliases
  # POST /virtual_aliases.json
  def create
    @virtual_alias = VirtualAlias.new(virtual_alias_params)

    respond_to do |format|
      if @virtual_alias.save
        format.html { redirect_to @virtual_alias, notice: 'Virtual alias was successfully created.' }
        format.json { render :show, status: :created, location: @virtual_alias }
      else
        format.html { render :new }
        format.json { render json: @virtual_alias.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /virtual_aliases/1
  # PATCH/PUT /virtual_aliases/1.json
  def update
    respond_to do |format|
      if @virtual_alias.update(virtual_alias_params)
        format.html { redirect_to @virtual_alias, notice: 'Virtual alias was successfully updated.' }
        format.json { render :show, status: :ok, location: @virtual_alias }
      else
        format.html { render :edit }
        format.json { render json: @virtual_alias.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /virtual_aliases/1
  # DELETE /virtual_aliases/1.json
  def destroy
    @virtual_alias.destroy
    respond_to do |format|
      format.html { redirect_to virtual_aliases_url, notice: 'Virtual alias was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_virtual_alias
      @virtual_alias = VirtualAlias.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def virtual_alias_params
      params.require(:virtual_alias).permit(:virtual_domain_id, :source, :destination)
    end
end

app/controllers/virtual_domains_controller.rb
class VirtualDomainsController < ApplicationController
  before_action :set_virtual_domain, only: [:show, :edit, :update, :destroy]

  # GET /virtual_domains
  # GET /virtual_domains.json
  def index
    @virtual_domains = VirtualDomain.all
  end

  # GET /virtual_domains/1
  # GET /virtual_domains/1.json
  def show
  end

  # GET /virtual_domains/new
  def new
    @virtual_domain = VirtualDomain.new
  end

  # GET /virtual_domains/1/edit
  def edit
  end

  # POST /virtual_domains
  # POST /virtual_domains.json
  def create
    @virtual_domain = VirtualDomain.new(virtual_domain_params)

    respond_to do |format|
      if @virtual_domain.save
        format.html { redirect_to @virtual_domain, notice: 'Virtual domain was successfully created.' }
        format.json { render :show, status: :created, location: @virtual_domain }
      else
        format.html { render :new }
        format.json { render json: @virtual_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /virtual_domains/1
  # PATCH/PUT /virtual_domains/1.json
  def update
    respond_to do |format|
      if @virtual_domain.update(virtual_domain_params)
        format.html { redirect_to @virtual_domain, notice: 'Virtual domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @virtual_domain }
      else
        format.html { render :edit }
        format.json { render json: @virtual_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /virtual_domains/1
  # DELETE /virtual_domains/1.json
  def destroy
    @virtual_domain.destroy
    respond_to do |format|
      format.html { redirect_to virtual_domains_url, notice: 'Virtual domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_virtual_domain
      @virtual_domain = VirtualDomain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def virtual_domain_params
      params.require(:virtual_domain).permit(:name)
    end
end

app/controllers/virtual_users_controller.rb
class VirtualUsersController < ApplicationController
  before_action :set_virtual_user, only: [:show, :edit, :update, :destroy]

  # GET /virtual_users
  # GET /virtual_users.json
  def index
    @virtual_users = VirtualUser.all
  end

  # GET /virtual_users/1
  # GET /virtual_users/1.json
  def show
  end

  # GET /virtual_users/new
  def new
    @virtual_user = VirtualUser.new
  end

  # GET /virtual_users/1/edit
  def edit
  end

  # POST /virtual_users
  # POST /virtual_users.json
  def create
    @virtual_user = VirtualUser.new(virtual_user_params)

    respond_to do |format|
      if @virtual_user.save
        format.html { redirect_to @virtual_user, notice: 'Virtual user was successfully created.' }
        format.json { render :show, status: :created, location: @virtual_user }
      else
        format.html { render :new }
        format.json { render json: @virtual_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /virtual_users/1
  # PATCH/PUT /virtual_users/1.json
  def update
    respond_to do |format|
      if @virtual_user.update(virtual_user_params)
        format.html { redirect_to @virtual_user, notice: 'Virtual user was successfully updated.' }
        format.json { render :show, status: :ok, location: @virtual_user }
      else
        format.html { render :edit }
        format.json { render json: @virtual_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /virtual_users/1
  # DELETE /virtual_users/1.json
  def destroy
    @virtual_user.destroy
    respond_to do |format|
      format.html { redirect_to virtual_users_url, notice: 'Virtual user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_virtual_user
      @virtual_user = VirtualUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def virtual_user_params
      params.require(:virtual_user).permit(:virtual_domain_id, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/virtual_aliases_helper.rb
module VirtualAliasesHelper
end

app/helpers/virtual_domains_helper.rb
module VirtualDomainsHelper
end

app/helpers/virtual_users_helper.rb
module VirtualUsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebmailDashboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/virtual_aliases/_form.html.erb
<%= form_with(model: virtual_alias, local: true) do |form| %>
  <% if virtual_alias.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(virtual_alias.errors.count, "error") %> prohibited this virtual_alias from being saved:</h2>

      <ul>
      <% virtual_alias.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :virtual_domain_id %>
    <%= form.text_field :virtual_domain_id, id: :virtual_alias_virtual_domain_id %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source, id: :virtual_alias_source %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination, id: :virtual_alias_destination %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/virtual_aliases/edit.html.erb
<h1>Editing Virtual Alias</h1>

<%= render 'form', virtual_alias: @virtual_alias %>

<%= link_to 'Show', @virtual_alias %> |
<%= link_to 'Back', virtual_aliases_path %>

app/views/virtual_aliases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Virtual Aliases</h1>

<table>
  <thead>
    <tr>
      <th>Virtual domain</th>
      <th>Source</th>
      <th>Destination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @virtual_aliases.each do |virtual_alias| %>
      <tr>
        <td><%= virtual_alias.virtual_domain %></td>
        <td><%= virtual_alias.source %></td>
        <td><%= virtual_alias.destination %></td>
        <td><%= link_to 'Show', virtual_alias %></td>
        <td><%= link_to 'Edit', edit_virtual_alias_path(virtual_alias) %></td>
        <td><%= link_to 'Destroy', virtual_alias, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Virtual Alias', new_virtual_alias_path %>

app/views/virtual_aliases/new.html.erb
<h1>New Virtual Alias</h1>

<%= render 'form', virtual_alias: @virtual_alias %>

<%= link_to 'Back', virtual_aliases_path %>

app/views/virtual_aliases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Virtual domain:</strong>
  <%= @virtual_alias.virtual_domain %>
</p>

<p>
  <strong>Source:</strong>
  <%= @virtual_alias.source %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @virtual_alias.destination %>
</p>

<%= link_to 'Edit', edit_virtual_alias_path(@virtual_alias) %> |
<%= link_to 'Back', virtual_aliases_path %>

app/views/virtual_domains/_form.html.erb
<%= form_with(model: virtual_domain, local: true) do |form| %>
  <% if virtual_domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(virtual_domain.errors.count, "error") %> prohibited this virtual_domain from being saved:</h2>

      <ul>
      <% virtual_domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :virtual_domain_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/virtual_domains/edit.html.erb
<h1>Editing Virtual Domain</h1>

<%= render 'form', virtual_domain: @virtual_domain %>

<%= link_to 'Show', @virtual_domain %> |
<%= link_to 'Back', virtual_domains_path %>

app/views/virtual_domains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Virtual Domains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @virtual_domains.each do |virtual_domain| %>
      <tr>
        <td><%= virtual_domain.name %></td>
        <td><%= link_to 'Show', virtual_domain %></td>
        <td><%= link_to 'Edit', edit_virtual_domain_path(virtual_domain) %></td>
        <td><%= link_to 'Destroy', virtual_domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Virtual Domain', new_virtual_domain_path %>

app/views/virtual_domains/new.html.erb
<h1>New Virtual Domain</h1>

<%= render 'form', virtual_domain: @virtual_domain %>

<%= link_to 'Back', virtual_domains_path %>

app/views/virtual_domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @virtual_domain.name %>
</p>

<%= link_to 'Edit', edit_virtual_domain_path(@virtual_domain) %> |
<%= link_to 'Back', virtual_domains_path %>

app/views/virtual_users/_form.html.erb
<%= form_with(model: virtual_user, local: true) do |form| %>
  <% if virtual_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(virtual_user.errors.count, "error") %> prohibited this virtual_user from being saved:</h2>

      <ul>
      <% virtual_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :virtual_domain_id %>
    <%= form.text_field :virtual_domain_id, id: :virtual_user_virtual_domain_id %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :virtual_user_password %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :virtual_user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/virtual_users/edit.html.erb
<h1>Editing Virtual User</h1>

<%= render 'form', virtual_user: @virtual_user %>

<%= link_to 'Show', @virtual_user %> |
<%= link_to 'Back', virtual_users_path %>

app/views/virtual_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Virtual Users</h1>

<table>
  <thead>
    <tr>
      <th>Virtual domain</th>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @virtual_users.each do |virtual_user| %>
      <tr>
        <td><%= virtual_user.virtual_domain %></td>
        <td><%= virtual_user.password %></td>
        <td><%= virtual_user.email %></td>
        <td><%= link_to 'Show', virtual_user %></td>
        <td><%= link_to 'Edit', edit_virtual_user_path(virtual_user) %></td>
        <td><%= link_to 'Destroy', virtual_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Virtual User', new_virtual_user_path %>

app/views/virtual_users/new.html.erb
<h1>New Virtual User</h1>

<%= render 'form', virtual_user: @virtual_user %>

<%= link_to 'Back', virtual_users_path %>

app/views/virtual_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Virtual domain:</strong>
  <%= @virtual_user.virtual_domain %>
</p>

<p>
  <strong>Password:</strong>
  <%= @virtual_user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @virtual_user.email %>
</p>

<%= link_to 'Edit', edit_virtual_user_path(@virtual_user) %> |
<%= link_to 'Back', virtual_users_path %>